### PR TITLE
added max height and scroll to control overflow

### PR DESCRIPTION
**Pull request by praveenebsco**

### CODE REVIEW

**Comment by wylie** [comment]
Hey @pivnickm & @esimons, can you two take a look at this?

**Comment by wylie** [comment]
I’m pretty sure you need to build this for dist so there’s is an updated `standalone` directory and JS file

**Comment by praveenebsco** [comment]
@wylie Is that an npm command ?? I see standalone folder specified inside bower.json file which I guess will take care of it.

**Comment by wylie** [comment]
@praveenebsco, I would check the `package.json` file. One of the scripts in there should create an updated `standalone` directory. 

We need to generate the deploy/dist/compiles files and push them to the `dist` branch or the tool tips won’t work

**Comment by wylie** [comment]
👍 just to check @praveenebsco , you've tested this locally? everything looks good on mobile and desktop?

**Comment by praveenebsco** [comment]
@wylie Yes. I tested the same using chrome dev tools simulating desktop, tablet and mobile devices. Will double check them again once its merged so that I can directly access it within DHUI.

**Pull request merged**
